//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pyrite.DatabaseCompiler.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pyrite.DatabaseCompiler.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO tblContacts (CONID, tblAssetID, tblComments, tblComputerName, tblContactCat, tblContactCell, tblContactEmail, tblContactEmpID, tblContactExtension, tblContactFax, tblContactLoginAdminLevel, tblContactLoginID, tblContactLoginPW, tblContactName, tblContactNameDisplay, tblContactNameFirst, tblContactNameLast, tblContactNickName, tblContactNumber, tblContactOffice, tblDeleted, tblDeletedBy, tblDepartment, tblNotes, tblResponsible1, tblResponsible10, tblResponsible2, tblResponsible3, tblResponsible4, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InsertTest {
            get {
                return ResourceManager.GetString("InsertTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT CONID, tblAssetID, tblComments, tblComputerName, tblContactCat, tblContactCell, tblContactEmail, tblContactEmpID, tblContactExtension, tblContactFax, tblContactLoginAdminLevel, tblContactLoginID, tblContactLoginPW, tblContactName, tblContactNameDisplay, tblContactNameFirst, tblContactNameLast, tblContactNickName, tblContactNumber, tblContactOffice, tblDeleted, tblDeletedBy, tblDepartment, tblNotes, tblResponsible1, tblResponsible10, tblResponsible2, tblResponsible3, tblResponsible4, tblResponsible5,  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SelectTest {
            get {
                return ResourceManager.GetString("SelectTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO tblContacts (CONID, tblAssetID, tblComments, tblComputerName, tblContactCat, tblContactCell, tblContactEmail, tblContactEmpID, tblContactExtension, tblContactFax, tblContactLoginAdminLevel, tblContactLoginID, tblContactLoginPW, tblContactName, tblContactNameDisplay, tblContactNameFirst, tblContactNameLast, tblContactNickName, tblContactNumber, tblContactOffice, tblDeleted, tblDeletedBy, tblDepartment, tblNotes, tblResponsible1, tblResponsible10, tblResponsible2, tblResponsible3, tblResponsible4, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UserValuesTest {
            get {
                return ResourceManager.GetString("UserValuesTest", resourceCulture);
            }
        }
    }
}
